# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as services.
# These services are built from the Dockerfile in their respective current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  frontend:
    build:
      context: frontend/
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/public:/usr/src/app/public
    depends_on:
      - backend
    healthcheck:
      test: curl -f http://localhost:3000/healthcheck || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 10s
    develop:
      watch:
        - path: .
          action: rebuild
  #----------------------------------------------------------------
  backend:
    build:
      context: backend/
      target: final
    ports:
      - "4000:4000"
    volumes:
      - ./backend/database:/database
    healthcheck:
      test: curl -f http://localhost:4000/healthcheck || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 10s
    develop:
      watch:
        - path: .
          action: rebuild
