import { ScrollArea } from "@/components/ui/scroll-area";
import NavigationBar from "@/components/uiperso/NavigationBar";
import SideBarList from "@/components/uiperso/sidebarlist";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col gap-2 bg-muted w-full h-screen p-5">
          <header>
            <NavigationBar />
          </header>
          <main className="flex h-full">
            <aside className="bg-background h-full rounded-lg">
              <SideBarList />
            </aside>
            <ScrollArea className="h-full w-full">
              <section className="flex-1 w-full max-h-96 bg-muted">
                {children}
              </section>
            </ScrollArea>
          </main>
        </div>
      </body>
    </html>
  );
}
